### ISSUE TITLE
Error loading custom controller with x-router-controller

### ISSUE THREAD

**Issue by DiV666** [oas-tools/oas-tools#110]
Hello,

When using the parameter x-router-controller I get the following error:
```
info: Valid specification file
info: Specification file dereferenced
debug: Register: GET - /health
debug:   GET - /health
debug:     OAS-doc has x-router-controller property
error: undefined
```

My configuration is:
```
SwaggerTools.configure({
    controllers: `${__dirname}/controllers`,
    ...
});
```

And my swagger.yaml definition is:
```
paths:
  /health:
    get:
      x-router-controller: health.controller
      operationId: getHealthStatus
```

I have seen in the function `checkControllers()` that when the parameter `x-router-controller` is used, the value is parsed with the function `utils.generateName(controller, undefined)`, eliminating the point that I have put to the controller file. Is this a requirement for the names of the controllers files or is it a bug?
