### ISSUE TITLE
nullable:true doesn't accept null value

### ISSUE THREAD

**Issue by SlytherinCz** [oas-tools/oas-tools#164]
oas-tools version 2.1.6
openapi: 3.0.0

**Schema**
```
...
company:
  type: object
  properties:
    taxDomicile:
      nullable: true
      type: string
      minLength: 3
      maxLength: 3
...
```

**Request**
```
...
"company": {
        "taxDomicile": null
    }
...
```

**Message during validation**
```
...{"code":"INVALID_TYPE","params":["string","null"],"message":"Expected type string but found type null","path":"#/comp
any/taxDomicile"}...
```

I expected that `nullable` would allow me to send `null`. I can only work around this by not sending the field at all. That approach would mean I would have to sanitize each outgoing message on client, which is something i would very happily avoid.

Is this expected behavior?
