### ISSUE TITLE
ReadOnly and writeOnly parameters are not validated correctly

### ISSUE THREAD

**Issue by adambordas** [oas-tools/oas-tools#169]
```
Pet:
      required:
        - id
        - name
        - tag
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        name:
          type: string
        tag:
          type: string
          writeOnly: true
```

The schema above incorrectly throws an error for these cases:
* Sending a POST request without `id`
* Sending a response body to a request without `tag`

According to the official documentation, both cases should be allowed.

> If a readOnly or writeOnly property is included in the required list, required affects just the relevant scope – responses only or requests only. That is, read-only required properties apply to responses only, and write-only required properties – to requests only.
https://swagger.io/docs/specification/data-models/data-types/
