### ISSUE TITLE
Validation for "format": "date-time"

### ISSUE THREAD

**Issue by alexanto** [oas-tools/oas-tools#175]
### Expected Behavior
In swagger-tools dates were validated if they matched the ISO format. If the parameter is an invalid string an error should be thrown. 

Example from docs:
```
- name: interval_end
  in: query
  description: End time. Accepts ISO formatted string.
  schema:
    type: string
    format: date-time
```

### Current Behavior
Invalid strings pass validation, and have to be checked manually.
