### ISSUE TITLE
Query parameter serialization

### ISSUE THREAD

**Issue by olvresc** [oas-tools/oas-tools#248]
Hi, following OpenAPI 3.0 spec https://swagger.io/docs/specification/serialization but it doesn't seem to work for me.

 ```
- in: query
   name: fields
   schema:
    type: array
    items:
     type: string
   style: form
   explode: false
```
```?fields=one,two,three```

### Expected Results:
```['one', 'two', 'three']```

### Current Results:
```['one,two,three']```
