### ISSUE TITLE
req.swagger not populated inside securityFile callback

### ISSUE THREAD

**Issue by pogotc** [oas-tools/oas-tools#326]
I've noticed that if in my swagger.yaml I have a route such as:

```yaml
"/{institution}/users":
    get: 
        x-swagger-router-controller: getInstitutionUsersController
        operationId: getInstitutionUsers
```

If I visit `/test/users` and inside the `getInstitutionUsersController` I run `console.log(req.swagger)` then it'll log something like:

```json
{
    "params": {
        "institution": {
            "value": "test"
        }
    }
}
```

But if I do the same thing inside the `securityFile` callback like this:

```js
oasTools.configure({
    securityFile: {
        oauth2: function authorizeRequest(req, authOrSecDef, routeScopes, next) {
            console.log(req.swagger)
        }
    }
});
```

 `req.swagger` is `undefined`. I'm guessing the middleware that populates `req.swagger` is running after the security check? Or I'm doing something wrong? I'm migrating to `oas-tools` from `swagger-node-runner` / `swagger-tools` and this did work on those libraries.

The examples aren't the exact code I'm using so don't include everything but hopefully there's enough there to explain the issue.
