### ISSUE TITLE
[BUG] Method expected for parameters object in a path object

### ISSUE THREAD

**Issue by raoulkent** [oas-tools/oas-tools#337]
**Describe the bug**
Method wrongly expected for `parameters:` in `oas-file`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create new `oas-file.yaml` which contains a route parameterised. Such as `foo/{bar}`.
2. Populate the route with an HTTP method (GET, POST, etc.)
3. Add a block to your route with parameter specification.
4. Also create a dummy controller named `foobar` with a dummy method named `doStuff`

```yaml
foo/{bar}:
  x-router-controller: foobar
  get:
    operationId: doStuff
  parameters:
    - name: bar
      in: path
      schema:
        type: string
        enum:
          - baz
          - qux
      required: true
```

When running you should get an error saying ~ `... does not have method funcfoobar`
If you then comment out the parameters object the application should start.

**Expected behavior**
the `parameters` block in the `yaml` should not be treated as a HTTP method. Thus oas-tools should not expect parameters to be bound to any method in the associated controller, whether default named or specified with `x-router-controller`
